#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [29]:
np.size(np.zeros(10))*np.zeros(10).itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
np.zeros(10)[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
(np.arange(10,50))[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [30]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random((3,3,3))

array([[[0.85441388, 0.25340753, 0.73601251],
        [0.30276452, 0.46947791, 0.29454614],
        [0.4631743 , 0.65119156, 0.51926337]],

       [[0.30802019, 0.03487164, 0.60163087],
        [0.13065148, 0.44477056, 0.61166116],
        [0.11866296, 0.37696732, 0.75392248]],

       [[0.72483859, 0.80124307, 0.32429722],
        [0.2997352 , 0.42618975, 0.07105668],
        [0.2037589 , 0.0210344 , 0.50327732]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [33]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
xmin, xmax

(0.02247827406364522, 0.9920516438579666)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [35]:
np.random.random(30).mean()

0.4743022848842267

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [38]:
np.array([[1,1,1],[1,0,1],[1,1,1]])

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [41]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [43]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [44]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [46]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [47]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [48]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [50]:
x = np.random.random((5,5))
x = (x - np.mean (x)) / (np.std (x))
x

array([[-0.28037787, -0.87249023, -1.1603968 ,  0.97362602,  0.81234388],
       [ 0.06512749,  0.76631953,  0.92929588, -1.6024849 , -1.77368502],
       [ 1.17685302, -1.69854638,  1.32098737,  0.67195578,  0.16404863],
       [-0.08047294,  0.82057652,  0.39235965, -1.71172054,  0.33931464],
       [ 0.63869826,  1.03390599,  0.05504393, -1.41318052,  0.43289861]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [51]:
np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [52]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [53]:
x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [54]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [57]:
Z**Z
Z <- Z
1j*Z
Z/1/1

array([[0.94115028, 0.67101617, 0.66188377, 0.06318039, 0.21102601,
        0.49039213, 0.57946747, 0.30346401, 0.63675027, 0.36786595],
       [0.83834059, 0.82907084, 0.16037002, 0.02682717, 0.01381239,
        0.54241014, 0.01491655, 0.94672691, 0.69827354, 0.10998399],
       [0.80129861, 0.33667266, 0.69701001, 0.93183659, 0.97194518,
        0.36702729, 0.8883785 , 0.67846543, 0.01340821, 0.00364595],
       [0.34161868, 0.28977267, 0.71535513, 0.03744388, 0.12503984,
        0.9661862 , 0.27462482, 0.37335668, 0.15181478, 0.68181472],
       [0.39966527, 0.8652091 , 0.74541262, 0.01233074, 0.33853845,
        0.15556245, 0.42349379, 0.61294563, 0.50684243, 0.57710997],
       [0.97034052, 0.62583537, 0.01925565, 0.94755901, 0.10776919,
        0.74858921, 0.81080172, 0.0877604 , 0.08563531, 0.19484503],
       [0.0896288 , 0.23678644, 0.54147935, 0.36508471, 0.51525647,
        0.98003535, 0.30023056, 0.5358545 , 0.98854359, 0.64276699],
       [0.35400795, 0.69093744, 0.1573297

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [58]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-58-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-58-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-58-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [59]:
np.where(Z>0, np.ceil(Z), np.floor(Z))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 30. How to find common values between two arrays? (★☆☆)

In [60]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))

[1 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [62]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [63]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [65]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(numpy.datetime64('2024-11-13'),
 numpy.datetime64('2024-11-14'),
 numpy.datetime64('2024-11-15'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [66]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [67]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [69]:
x = np.random.uniform(0,10,10)

print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[1. 8. 9. 9. 7. 6. 7. 2. 3. 1.]
[1. 8. 9. 9. 7. 6. 7. 2. 3. 1.]
[1. 8. 9. 9. 7. 6. 7. 2. 3. 1.]
[1 8 9 9 7 6 7 2 3 1]
[1. 8. 9. 9. 7. 6. 7. 2. 3. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [70]:
x = np.zeros((5,5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [71]:
def generate():
    for x in range(10):
        yield x
y = np.fromiter(generate(),dtype=float,count=-1)
y

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [72]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [76]:
x = np.random.random(10)
x.sort()
x

array([0.15523299, 0.16525072, 0.20630372, 0.24313458, 0.31186821,
       0.40922919, 0.44014111, 0.4981453 , 0.69081049, 0.71312608])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [79]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [81]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [84]:
x = np.zeros(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [88]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[1.18048105 0.48880314 1.10217263 1.08579117 0.20109356 0.81299161
 0.64491466 0.41002053 1.1808061  0.63854409]
[0.83300796 0.42710694 0.82600244 1.16592898 1.56893816 1.05156548
 1.56505197 0.74549075 0.81797494 1.57024309]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [89]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.37881433 0.63801049 0.33686094 0.53839981 0.1121605  0.16675086
 0.90082012 0.         0.13252994 0.06782438]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [90]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [92]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [93]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [96]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [97]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

20


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [98]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-98-504447058529>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [99]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.3656803  0.23646095 0.48784219 0.14650514 0.41415062
  0.43919399 0.53740458 0.10491712 0.21739422]
 [0.3656803  0.         0.59998511 0.14180469 0.23150758 0.2473681
  0.59583006 0.19170472 0.26540762 0.16023906]
 [0.23646095 0.59998511 0.         0.72430258 0.38194693 0.63473622
  0.5161409  0.77383535 0.34114728 0.45375313]
 [0.48784219 0.14180469 0.72430258 0.         0.34376834 0.21910615
  0.62905805 0.05080718 0.38337791 0.27084657]
 [0.14650514 0.23150758 0.38194693 0.34376834 0.         0.27826688
  0.42941188 0.39262088 0.04249487 0.07344625]
 [0.41415062 0.2473681  0.63473622 0.21910615 0.27826688 0.
  0.41917864 0.2405153  0.31914142 0.23285696]
 [0.43919399 0.59583006 0.5161409  0.62905805 0.42941188 0.41917864
  0.         0.65779518 0.43451708 0.46466592]
 [0.53740458 0.19170472 0.77383535 0.05080718 0.39262088 0.2405153
  0.65779518 0.         0.43272616 0.32010924]
 [0.10491712 0.26540762 0.34114728 0.38337791 0.04249487 0.31914142
  0.43451708 0.4327261

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [100]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[33 12  8 90 59 51 97 92 78 33]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [103]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [104]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [105]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [106]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [107]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.35778194 -0.16150127  0.08889533  0.07911009 -0.22777315  0.53521587
  -0.24995282 -0.32036037  0.06541677  0.5487315 ]
 [ 0.36252421 -0.42325462 -0.24947396  0.21986575  0.24872891  0.35225539
  -0.42998262 -0.1552717   0.44914957 -0.37454093]
 [-0.35979213 -0.27174119 -0.08448957 -0.13637724  0.41285117  0.26323101
  -0.13012838  0.47181758 -0.05789021 -0.10748106]
 [-0.47787044 -0.28402224  0.14811851 -0.22880765  0.01367381  0.26239879
   0.29536507 -0.08673946  0.02548974  0.33239387]
 [ 0.01281708 -0.14821077  0.36532488 -0.03629593 -0.30797549 -0.04334999
  -0.28859961  0.1740311  -0.10544876  0.3777075 ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [108]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 9 1]
 [0 0 6]
 [7 5 3]]
[[0 0 6]
 [7 5 3]
 [7 9 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [109]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [110]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4147737013031423


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [111]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [112]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [113]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 3. 3. 2. 1. 5. 4. 2. 3. 6.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [114]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [115]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [116]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[64 63 60 50]
 [58 50 45 50]
 [39 46 57 47]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [118]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(pd.Series(D).groupby(S).mean())

0    0.549361
1    0.526404
2    0.513034
3    0.652622
4    0.512925
5    0.584833
6    0.482653
7    0.476700
8    0.601149
9    0.324253
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [119]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.70428311, 0.79069133, 1.65982087, 1.58281641, 0.8006237 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [120]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [121]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [122]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [123]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 47) ( 0, 97) ( 1, 55) ( 1, 75) ( 5, 55) ( 5, 91) ( 7,  8) ( 7, 47)
 ( 8, 47) ( 9, 67) ( 9, 72) (12, 35) (12, 37) (34, 34) (34, 46) (35, 37)
 (37, 89) (37, 92) (41, 65) (41, 98) (47, 97) (55, 75) (55, 91) (61, 82)
 (61, 85) (65, 98) (67, 72) (82, 85) (89, 92)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [124]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [125]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [126]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [127]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.92140931, -0.41089069,  0.28918402,  0.6178386 , -0.32772262,
       -0.12369328, -0.79907172, -0.94597831, -0.22940562, -0.65129292,
        0.5534209 ,  0.41280815, -0.03486617, -0.25317119, -0.8729815 ,
       -0.44948983,  0.81755948, -0.85048839,  0.9731698 , -0.03439173,
       -0.243771  , -0.11826231,  0.37927889, -0.89069931,  0.32408578,
       -0.04770426, -0.67916473, -0.37440576, -0.89310715,  0.82449598,
       -0.98279712, -0.98237829,  0.91507978,  0.75160909, -0.56389373,
        0.39346324, -0.24113834, -0.38998892, -0.06472869, -0.88268547,
       -0.93118045,  0.01006442,  0.86342607,  0.2828229 ,  0.72265253,
       -0.7066407 , -0.42306564,  0.37852286,  0.57110311,  0.03048332,
        0.58245258, -0.17497206, -0.54279404,  0.25077677, -0.4399493 ,
        0.36797732,  0.23817584,  0.70525552, -0.84572812, -0.52561368,
       -0.91530712, -0.84625718, -0.07326787, -0.8292958 ,  0.71798179,
       -0.38296626,  0.18104594, -0.60545185,  0.07042673, -0.76

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [128]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.31029336  2.20248888  1.05519823  2.501492    1.76496034  3.17600911
 10.75208664  4.45640983  1.06297023  1.21237194]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [129]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.04491705 14.56645322  5.42822998  4.57072725  2.5394746   3.31072205
   6.88110565  4.64334069  3.78061219  2.23493539]
 [ 4.18713517  4.72420722  4.04125955  0.06254305  3.32525261  9.9735526
   0.87221524 15.27357895  9.08020645 10.45700967]
 [10.00232908  0.76133521  8.32258565 10.09840259 10.11369738  4.42889645
   7.91753343  2.65504468  5.28829463  7.55426469]
 [ 3.76232342 15.69993598  2.1922615   2.6893376   1.50759786  2.37097214
   5.74075952  1.44162069  7.84190722  6.00146446]
 [10.27717414  6.41314243  6.35775613  6.68364622  9.20356129  6.56404442
   3.83652077  1.77680187  1.20912085  1.05909311]
 [ 3.30654048  5.87695157  3.81216446  0.31375347  2.77700869  8.6265383
   1.3647093  13.46807849  7.27641398  8.70474143]
 [11.5682085   1.00217534  9.42604623 10.79216709 11.45819343  6.23801911
   8.38425036  0.76680612  4.10935133  6.47167221]
 [ 9.4661721   0.32369189  8.33054035 10.49292304  9.85818286  3.4846011
   8.50174904  4.03442463  6.81623112  9.05183215]
 [ 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [130]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [131]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [132]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [133]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [134]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 1 1]
   [0 1 1]
   [4 2 0]]

  [[1 1 3]
   [1 1 0]
   [2 0 1]]

  [[1 3 1]
   [1 0 0]
   [0 1 1]]

  [[3 1 1]
   [0 0 1]
   [1 1 2]]

  [[1 1 0]
   [0 1 1]
   [1 2 0]]

  [[1 0 4]
   [1 1 0]
   [2 0 3]]

  [[0 4 2]
   [1 0 2]
   [0 3 0]]

  [[4 2 4]
   [0 2 0]
   [3 0 4]]]


 [[[0 1 1]
   [4 2 0]
   [3 2 1]]

  [[1 1 0]
   [2 0 1]
   [2 1 3]]

  [[1 0 0]
   [0 1 1]
   [1 3 2]]

  [[0 0 1]
   [1 1 2]
   [3 2 1]]

  [[0 1 1]
   [1 2 0]
   [2 1 1]]

  [[1 1 0]
   [2 0 3]
   [1 1 2]]

  [[1 0 2]
   [0 3 0]
   [1 2 1]]

  [[0 2 0]
   [3 0 4]
   [2 1 2]]]


 [[[4 2 0]
   [3 2 1]
   [2 0 1]]

  [[2 0 1]
   [2 1 3]
   [0 1 2]]

  [[0 1 1]
   [1 3 2]
   [1 2 1]]

  [[1 1 2]
   [3 2 1]
   [2 1 0]]

  [[1 2 0]
   [2 1 1]
   [1 0 2]]

  [[2 0 3]
   [1 1 2]
   [0 2 3]]

  [[0 3 0]
   [1 2 1]
   [2 3 0]]

  [[3 0 4]
   [2 1 2]
   [3 0 3]]]


 [[[3 2 1]
   [2 0 1]
   [2 4 2]]

  [[2 1 3]
   [0 1 2]
   [4 2 4]]

  [[1 3 2]
   [1 2 1]
   [2 4 4]]

  [[3 2 1]
   [2 1 0]
   [4 4 3]]

  [[2 1 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [135]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  8 10  9  4]
 [ 8  9 17 14  5]
 [10 17  5 42  0]
 [ 9 14 42  6  4]
 [ 4  5  0  4  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [136]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [137]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [138]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [139]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [140]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [141]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [142]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.31 s ± 51.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
219 ms ± 9.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
198 ms ± 14.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [143]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [146]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[3 1 2]
 [4 2 2]
 [2 0 1]
 [1 2 0]
 [4 4 0]
 [4 3 0]
 [1 1 4]
 [1 2 0]
 [4 3 4]
 [2 2 1]]
[[3 1 2]
 [4 2 2]
 [2 0 1]
 [1 2 0]
 [4 4 0]
 [4 3 0]
 [1 1 4]
 [1 2 0]
 [4 3 4]
 [2 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [147]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [148]:
uZ = np.unique(Z, axis=0)
print(uZ)

[[1 1 4]
 [1 2 0]
 [2 0 1]
 [2 2 1]
 [3 1 2]
 [4 2 2]
 [4 3 0]
 [4 3 4]
 [4 4 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [149]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[1.32445361e-01, 3.41869774e-02, 2.80354765e-02, 1.87874377e-01,
        5.73658889e-02, 1.20833049e-01, 6.74630434e-03, 3.78162876e-03,
        2.05580835e-02, 1.85964437e-01],
       [1.54599988e-01, 3.99055602e-02, 3.27250749e-02, 2.19300822e-01,
        6.69616944e-02, 1.41045242e-01, 7.87478374e-03, 4.41419586e-03,
        2.39969106e-02, 2.17071399e-01],
       [3.25033594e-01, 8.38981153e-02, 6.88017431e-02, 4.61061706e-01,
        1.40781383e-01, 2.96535870e-01, 1.65560767e-02, 9.28047900e-03,
        5.04515049e-02, 4.56374530e-01],
       [4.90396365e-02, 1.26581780e-02, 1.03805038e-02, 6.95629587e-02,
        2.12404747e-02, 4.47400254e-02, 2.49790790e-03, 1.40019778e-03,
        7.61190077e-03, 6.88557781e-02],
       [1.05581810e-02, 2.72529209e-03, 2.23491130e-03, 1.49768301e-02,
        4.57305135e-03, 9.63247932e-03, 5.37796882e-04, 3.01461075e-04,
        1.63883404e-03, 1.48245749e-02],
       [3.04644424e-01, 7.86352349e-02, 6.44858494e-02, 4.32139571e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [151]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [152]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [153]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.27615973  0.09645453]
